baseURL = "https://heatherwiedphotography.com/"
languageCode = "en-us"
title = "Heather Wied Photography"
theme = [] # We are building custom layouts, so no theme needed

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Needed for raw HTML in templates if used

[params]
  description = "Example photo galleries"
  author = "Your Name"
  
  # Tailwind Support
  # Ensure you run `npx tailwindcss -i ./assets/css/input.css -o ./static/css/style.css --watch` during dev
